### PR TITLE
Fix: Handle ClassCastException in ForgeDataType.serialize

### PR DESCRIPTION
**Pull request by dev-ainz**
Fix: Handle ClassCastException in ForgeDataType.serialize

- Added a check to convert Integer to Long when necessary.
- Ensures compatibility with generic types in ForgeDataType.

### CODE REVIEW

**Comment by Speiger** [comment]
@CarlosATeixeira could you explain why a conversion of a type change is needed?
Like could you provide a example?

Because if a config switches types on the fly then it is using the wrong type.

**Comment by CarlosATeixeira** [comment]
> @CarlosATeixeira could you explain why a conversion of a type change is needed? Like could you provide a example?
> 
> Because if a config switches types on the fly then it is using the wrong type.

There is no issue with CarbonConfig itself. As a Modpack Maker, I have noticed that many mods contain poorly written code, such as sending a Long value to an Integer serializer. While this problem is not caused by CarbonConfig, this change will help prevent those faulty mod configurations from completely crashing the game.

**Comment by dev-ainz** [comment]
> @CarlosATeixeira could you explain why a conversion of a type change is needed? Like could you provide a example?
> 
> Because if a config switches types on the fly then it is using the wrong type.

There is no issue with CarbonConfig itself. As a Modpack Maker, I have noticed that many mods contain poorly written code, such as sending a Long value to an Integer serializer. While this problem is not caused by CarbonConfig, this change will help prevent those faulty mod configurations from completely crashing the game.

**Comment by Speiger** [comment]
@CarlosATeixeira could you provide an example mod so I can investigate it too?
That way I can look if there isn't a better solution.
If not, then i will merge and propagierte this patch around all version.

**Comment by dev-ainz** [comment]
> @CarlosATeixeira could you provide an example mod so I can investigate it too? That way I can look if there isn't a better solution. If not, then i will merge and propagierte this patch around all version.

The mod EquipmentCompare is causing the game to crash with the following error:

`carbonconfiglib.gui.impl.forge.ForgeDataType.serialize(ForgeDataType.java:79)`

...when attempting to access config.visual_options through the GUI.

**Comment by Speiger** [comment]
Ok I looked into this and I know why it happens.
Its a Carbon Config specific issue in combination with the config library forge/neoforge uses...
The main issue is that generic types can change in there and forge stores them as numbers, not as specific types.
So the solution is to refactor ForgeDataTypes to be typeless. Which isn't easy since i kinda need the typing for the parsing but not for the serialization...

Anyways, this patch is more of a bandate not an actual fix. And i rather want to have this fixed.
If you want to help, you can try to do  this patch since i am extremely busy atm and only have really time to work on weekend on this (and the weekend for me is effectively over)

I will try to come up with impl solutions during the week but no promises.

Thank you for the PR (leaving it open till the issue is fixed)

**Comment by dev-ainz** [comment]
Updated to be Typeless.
Tested with EquipmentCompare and it worked.

**Comment by Speiger** [comment]
@CarlosATeixeira please keep the formatting how it was before.
doesn't have to be 100% exact but don't break it like you just did.
Minor things i can clean up.
Other than that i will look into it on the weekend.

Also thank you for the hard work!

**Comment by Speiger** [comment]
@CarlosATeixeira just to give you a headsup i will look into merging/improving this patch tomorrow.
I looked over it, and the concept is fine. It just needs a few refinements that are just my opinion (also a code reformatting)

Thank you for the help :)

**Review by Speiger — APPROVED** [review]
LGTM

**Comment by Speiger** [comment]
@CarlosATeixeira next time please don't let your Intellij formatter run over the files.
Anyways i integrated the code into my local branch and tested it after the cleanup.

I will push out the update over the next week ish. Since i need to migrate it between all mc versions that support that feature.

**Comment by dev-ainz** [comment]
@Speiger, sorry about the issues caused by the IntelliJ formatter and for not paying closer attention to this. Unfortunately, I couldn't dedicate as much time to refining everything as I would have liked.

Thank you for reviewing, improving, and integrating the patch despite these issues. I’ll make sure to avoid similar mistakes in the future!

**Comment by Speiger** [comment]
@CarlosATeixeira no problem.
I thank you for kickstarting the project, it helps getting things rolling that way.

**Pull request merged**
